version: "3"
services:
mqtt:
    image: eclipse-mosquitto
    volumes:
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    networks:
      - backend
      - traefik_proxy
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
    deploy:
      labels:
        - "traefik.port=9001"
        - "traefik.protocol=ws"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.rule=Host:${client}.twcreativs.stream; PathPrefixStrip: /mqtt"

nodered:
    image: nodered/node-red-docker
    networks:
      - backend
      - traefik_proxy
    volumes:
      - node_data:/data
    depends_on:
      - mqtt
    deploy:
      labels:
        - "traefik.port=1880"
        - "traefik.docker.network=traefik_proxy"
        - "traefik.frontend.rule=Host:${client}.twcreativs.stream; PathPrefixStrip: /nodered"


networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    backend:

volumes:
    node_data:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.94,rw
          device: ":/NFS_VOL/HDD/${client}/node_data"
    mqtt_data:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.94,rw
          device: ":/NFS_VOL/HDD/${client}/mqtt_data"
    mqtt_log:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.94,rw
          device: ":/NFS_VOL/HDD/${client}/mqtt_log"