version: "3"
services:

    database:
        image: mongo:4
        networks:
            - backend
        environment:
            - MONGO_INITDB_DATABASE=streamingVod
        volumes:
            - vod_db:/data/db
        restart: always
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: 300M

    web:
        image: weslleycsil/vod-streaming:1.7.0
        environment:
            - NODE_ENV=production
            - CLIENT=${client}
            - videoApiUrl=${urlApi}
            - p480_low=${p480_low}
            - p480=${p480}
            - p720=${p720}
            - p1080=${p1080}
            - bck=${bck}
        volumes:
            - vod_upload:/usr/src/app/uploads/
            - vod_files:/usr/src/app/files/
        networks:
            - traefik_proxy
            - backend
            - redis-net
        depends_on:
            - database
        deploy:
          labels:
            - "traefik.web.port=8080"
            - "traefik.kue.port=3001"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.web.frontend.rule=Host:${client}.${urlsite}; PathPrefixStrip: /api/videos"
            - "traefik.kue.frontend.rule=Host:${client}.${urlsite}; PathPrefixStrip: /kue"
          resources:
            limits:
              cpus: '0.1'
              memory: 300M

        command: npm start
        working_dir: /usr/src/app
        
    redis:
        image: redis:buster
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        networks:
          - redis-net
        volumes:
          - vod_redis:/data
        deploy:
          resources:
            limits:
              cpus: '0.5'
              memory: 300M

    encoder:
        image: weslleycsil/encoder-streaming:1.4.6
        environment:
            - NODE_ENV=production
            - CLIENT=${client}
            - amb=production
            - Videos=3
            - Thumbs=4
        volumes:
            - vod_upload:/usr/src/app/uploads/
            - vod_files:/usr/src/app/files/
        networks:
            - redis-net
        command: npm start
        working_dir: /usr/src/app
        deploy:
          resources:
            limits:
              cpus: '3.0'
              memory: 2000M

networks:
    traefik_proxy:
        external:
            name: traefik_proxy
    backend:
    redis-net:

volumes:
    aod_audios:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.93,rw
          device: ":/NFS_VOL/HDD/${client}/aod-audios"
    vod_upload:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.93,rw
          device: ":/NFS_VOL/HDD/${client}/vod-upload"
    vod_files:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.93,rw
          device: ":/NFS_VOL/HDD/${client}/vod-files"
    vod_redis:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.93,rw
          device: ":/NFS_VOL/SSD/${client}/vod-redis"
    vod_db:
        driver: local
        driver_opts:
          type: nfs
          o: nfsvers=4,addr=10.10.10.93,rw
          device: ":/NFS_VOL/SSD/${client}/vod-db"
